# Generated by Django 4.2.3 on 2023-08-02 19:57

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(null=True, upload_to=job.models.image_upload),
        ),
    ]
